# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: Copyright (c) 2026 Andrew Wyatt (Fewtarius)

package CLIO::Util::ImageDisplay;

use strict;
use warnings;
use utf8;
use Carp qw(croak);
use CLIO::Core::Logger qw(log_debug log_warning);
use CLIO::UI::Terminal qw(supports_inline_images terminal_image_protocol);

=head1 NAME

CLIO::Util::ImageDisplay - Display images inline in the terminal

=head1 DESCRIPTION

Supports kitty graphics protocol, iTerm inline images, sixel (via img2sixel),
and fallback to saving images to disk. Used for displaying images received
from AI models or generated by image generation tools.

=head1 DEPENDENCIES

=over 4

=item * L<MIME::Base64> - Core Perl module for base64 encoding/decoding

=item * L<File::Temp> - Core Perl module for temporary file creation (sixel support)

=item * L<HTTP::Tiny> - Core Perl module for downloading images from URLs (used by Chat.pm)

=item * img2sixel - Optional external command from libsixel for sixel protocol support

=back

=head1 SYNOPSIS

    use CLIO::Util::ImageDisplay;
    
    my $display = CLIO::Util::ImageDisplay->new();
    $display->show_image($image_data, 'image/png');
    
    # Or display from a file
    $display->show_image_file('/path/to/image.png');

=cut

# kitty graphics protocol constants
my $KITTY_ESC = "\e_G";
my $KITTY_ST  = "\e\\";

# iTerm inline image constants
my $ITERM_ESC = "\e]1337;";

=head2 new(%opts)

Create a new ImageDisplay instance.

Options:
- output_dir: Directory to save images when terminal doesn't support inline display
- max_width: Maximum width in pixels (default: 800)
- max_height: Maximum height in pixels (default: 600)

=cut

sub new {
    my ($class, %opts) = @_;
    
    my $self = bless {
        protocol       => terminal_image_protocol(),
        output_dir     => $opts{output_dir} // _default_output_dir(),
        max_width      => $opts{max_width} // 800,
        max_height     => $opts{max_height} // 600,
        displayed_count => 0,
    }, $class;
    
    # Ensure output directory exists
    unless (-d $self->{output_dir}) {
        eval { require File::Path; File::Path::make_path($self->{output_dir}); };
        if ($@) {
            log_debug('ImageDisplay', "Cannot create output directory: $self->{output_dir}");
            $self->{output_dir} = '.';
        }
    }
    
    log_debug('ImageDisplay', "Protocol: " . ($self->{protocol} // 'none') . 
        ", output_dir: $self->{output_dir}");
    
    return $self;
}

=head2 show_image($data, $mime_type, %opts)

Display image data inline in the terminal, or save to file if terminal
 doesn't support inline images.

Arguments:
- $data: Raw binary image data or base64-encoded string
- $mime_type: MIME type (e.g., 'image/png', 'image/jpeg')
- %opts: Optional parameters
  * filename: Suggested filename for saved images
  * alt: Alt text for accessibility

Returns: ($success, $display_info)
  - $success: 1 if displayed/saved successfully
  - $display_info: Hash with 'path' (saved file path) or 'inline' => 1

=cut

sub show_image {
    my ($self, $data, $mime_type, %opts) = @_;
    
    return (0, { error => 'No image data' }) unless defined $data && length($data) > 0;
    
    # Determine if data is base64 or raw binary
    # Prefer explicit flag from caller; fall back to heuristic
    my $is_base64;
    if (defined $opts{is_base64}) {
        $is_base64 = $opts{is_base64};
    } else {
        # Heuristic: base64 data is ASCII-safe chars only, typically longer than 100 bytes
        # and contains no high-bit characters (0x80-0xFF) that raw binary would have
        $is_base64 = ($data =~ /^[A-Za-z0-9+\/\n\r]+={0,2}$/ && length($data) > 100);
    }
    my $binary_data = $is_base64 ? _decode_base64($data) : $data;
    
    unless ($binary_data && length($binary_data) > 0) {
        return (0, { error => 'Invalid image data' });
    }
    
    # Try inline display first if supported
    if ($self->{protocol}) {
        my $ok = $self->_display_inline($binary_data, $mime_type, %opts);
        return (1, { inline => 1 }) if $ok;
    }
    
    # Fallback: save to file
    return $self->_save_to_file($binary_data, $mime_type, %opts);
}

=head2 show_image_file($file_path, %opts)

Display an image file inline in the terminal.

Arguments:
- $file_path: Path to the image file
- %opts: Same as show_image

Returns: Same as show_image

=cut

sub show_image_file {
    my ($self, $file_path, %opts) = @_;
    
    return (0, { error => 'File not found' }) unless -f $file_path;
    
    open my $fh, '<:raw', $file_path or return (0, { error => "Cannot read: $!" });
    local $/;
    my $data = <$fh>;
    close $fh;
    
    # Detect MIME type from file extension
    my $mime_type = 'image/png';
    if ($file_path =~ /\.jpe?g$/i) {
        $mime_type = 'image/jpeg';
    } elsif ($file_path =~ /\.gif$/i) {
        $mime_type = 'image/gif';
    } elsif ($file_path =~ /\.webp$/i) {
        $mime_type = 'image/webp';
    }
    
    return $self->show_image($data, $mime_type, %opts);
}

# ─────────────────────────────────────────────────────────────
# Private methods
# ─────────────────────────────────────────────────────────────

sub _display_inline {
    my ($self, $data, $mime_type, %opts) = @_;
    
    my $protocol = $self->{protocol} or return 0;
    
    if ($protocol eq 'kitty') {
        return $self->_display_kitty($data, $mime_type, %opts);
    }
    elsif ($protocol eq 'iterm') {
        return $self->_display_iterm($data, $mime_type, %opts);
    }
    elsif ($protocol eq 'sixel') {
        return $self->_display_sixel($data, $mime_type, %opts);
    }
    
    return 0;
}

sub _display_kitty {
    my ($self, $data, $mime_type, %opts) = @_;
    
    # kitty graphics protocol: transmit image data in chunks
    # Format codes: 100=RGB, 102=JPEG, 103=PNG
    # We always send base64-encoded data, so use the appropriate format code
    
    require MIME::Base64;
    my $base64 = MIME::Base64::encode_base64($data, '');
    
    # Determine format code based on actual image format
    my $format = 100;  # default: RGB (raw pixels)
    $format = 103 if $mime_type eq 'image/png';
    $format = 102 if $mime_type eq 'image/jpeg';
    
    # Get image dimensions if possible (optional but helps kitty scale)
    my ($width, $height) = _get_image_dimensions($data, $mime_type);
    
    # kitty graphics protocol: transmit then place
    # Step 1: Transmit image data (a=T)
    # Step 2: Place image (a=p) at cursor position
    
    # Build transmit control sequence
    # a=T (transmit), f=format, s=width, v=height, m=1 (more data follows)
    my $ctrl = "a=T,f=$format";
    $ctrl .= ",s=$width" if $width;
    $ctrl .= ",v=$height" if $height;
    
    # kitty has a 4096 byte payload limit per chunk
    my $chunk_size = 4096;
    my $pos = 0;
    my $total = length($base64);
    my $image_id = int(rand(1000000));  # Unique ID for placement reference
    
    while ($pos < $total) {
        my $chunk = substr($base64, $pos, $chunk_size);
        my $more = ($pos + $chunk_size < $total) ? 1 : 0;
        
        my $seq = $KITTY_ESC . $ctrl . ",i=$image_id,m=$more;" . $chunk . $KITTY_ST;
        print $seq;
        
        $pos += $chunk_size;
        $ctrl = '';  # Only first chunk needs control data
    }
    
    # Step 2: Place the transmitted image at cursor position
    my $place_seq = $KITTY_ESC . "a=p,i=$image_id" . $KITTY_ST;
    print $place_seq;
    print "\n";
    STDOUT->flush() if STDOUT->can('flush');
    
    log_debug('ImageDisplay', "Displayed image via kitty protocol (" . length($data) . " bytes, id=$image_id)");
    return 1;
}

sub _display_iterm {
    my ($self, $data, $mime_type, %opts) = @_;
    
    # iTerm inline image protocol
    # Format: \e]1337;File=name=base64name;size=<size>;inline=1:<base64_data>\a
    
    require MIME::Base64;
    my $base64 = MIME::Base64::encode_base64($data, '');
    
    my $filename = $opts{filename} // 'image.png';
    my $name_b64 = MIME::Base64::encode_base64($filename, '');
    chomp($name_b64);
    
    my $size = length($data);
    my $seq = $ITERM_ESC . "File=name=$name_b64;size=$size;inline=1:$base64\a";
    
    print $seq;
    print "\n";
    STDOUT->flush() if STDOUT->can('flush');
    
    log_debug('ImageDisplay', "Displayed image via iTerm protocol (" . length($data) . " bytes)");
    return 1;
}

sub _display_sixel {
    my ($self, $data, $mime_type, %opts) = @_;
    
    # Sixel requires converting the image to sixel format.
    # The most practical approach is to use img2sixel (from libsixel) if available.
    # Pure Perl sixel encoding is complex and would add significant code.
    
    # Check if img2sixel is available
    my $img2sixel = _find_command('img2sixel');
    unless ($img2sixel) {
        log_debug('ImageDisplay', "img2sixel not found, falling back to file save");
        return 0;
    }
    
    # Save image to a temp file, then pipe through img2sixel
    require File::Temp;
    my ($tmp_fh, $tmp_path) = File::Temp::tempfile(
        SUFFIX => _mime_to_ext($mime_type),
        UNLINK => 1,
    );
    binmode($tmp_fh, ':raw');
    print $tmp_fh $data;
    close $tmp_fh;
    
    # Run img2sixel and capture output
    my $output = `$img2sixel $tmp_path 2>/dev/null`;
    unlink $tmp_path;
    
    if (defined $output && length($output) > 0) {
        print $output;
        STDOUT->flush() if STDOUT->can('flush');
        log_debug('ImageDisplay', "Displayed image via sixel protocol (" . length($data) . " bytes)");
        return 1;
    }
    
    log_debug('ImageDisplay', "img2sixel produced no output, falling back to file");
    return 0;
}

sub _find_command {
    my ($name) = @_;
    for my $dir (split /:/, $ENV{PATH} // '/usr/bin:/bin') {
        my $path = "$dir/$name";
        return $path if -x $path;
    }
    return undef;
}

sub _mime_to_ext {
    my ($mime) = @_;
    return '.jpg'  if $mime eq 'image/jpeg';
    return '.gif'  if $mime eq 'image/gif';
    return '.webp' if $mime eq 'image/webp';
    return '.png';
}

sub _save_to_file {
    my ($self, $data, $mime_type, %opts) = @_;
    
    # Determine file extension from MIME type
    my $ext = 'png';
    $ext = 'jpg' if $mime_type eq 'image/jpeg';
    $ext = 'gif' if $mime_type eq 'image/gif';
    $ext = 'webp' if $mime_type eq 'image/webp';
    
    my $filename = $opts{filename} // ('image_' . time() . '_' . int(rand(10000)) . ".$ext");
    my $path = $self->{output_dir} . '/' . $filename;
    
    # Ensure unique filename
    my $counter = 1;
    my $orig_path = $path;
    while (-e $path) {
        $path = $orig_path;
        $path =~ s/\.$ext$/_$counter.$ext/;
        $counter++;
    }
    
    open my $fh, '>:raw', $path or return (0, { error => "Cannot write: $!" });
    print $fh $data;
    close $fh;
    
    $self->{displayed_count}++;
    
    log_debug('ImageDisplay', "Saved image to: $path (" . length($data) . " bytes)");
    
    return (1, { path => $path, saved => 1 });
}

# ─────────────────────────────────────────────────────────────
# Private helpers
# ─────────────────────────────────────────────────────────────

sub _decode_base64 {
    my ($data) = @_;
    my $result = eval {
        require MIME::Base64;
        return MIME::Base64::decode_base64($data);
    };
    if ($@) {
        log_debug('ImageDisplay', "Base64 decode failed: $@");
        return undef;
    }
    return $result;
}

sub _default_output_dir {
    my $home = $ENV{HOME} // $ENV{USERPROFILE} // '.';
    return "$home/.clio/images";
}

sub _get_image_dimensions {
    my ($data, $mime_type) = @_;
    
    return (undef, undef) unless defined $data && length($data) >= 24;
    
    if ($mime_type eq 'image/png') {
        # PNG: width at bytes 16-19, height at 20-23 (big-endian)
        my $width = unpack('N', substr($data, 16, 4));
        my $height = unpack('N', substr($data, 20, 4));
        return ($width, $height);
    }
    elsif ($mime_type eq 'image/jpeg') {
        # JPEG dimensions require parsing SOF markers - skip for now
        return (undef, undef);
    }
    elsif ($mime_type eq 'image/gif') {
        # GIF: width at bytes 6-7 (little-endian), height at 8-9
        my $width = unpack('v', substr($data, 6, 2));
        my $height = unpack('v', substr($data, 8, 2));
        return ($width, $height);
    }
    
    return (undef, undef);
}

=head1 AUTHOR

CLIO Project

=head1 LICENSE

GPL-3.0

=cut

1;