name: [BUG] Bug Report
description: Report a bug or unexpected behavior in CLIO
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before You Continue...
        
        **Have you checked these resources first?**
        - [DOC] [Documentation](https://github.com/SyntheticAutonomicMind/CLIO/tree/main/docs)
        -  [GitHub Discussions](https://github.com/SyntheticAutonomicMind/CLIO/discussions) - For questions and support
        - [SEARCH] [Existing Issues](https://github.com/SyntheticAutonomicMind/CLIO/issues) - Your issue may already be reported
        
        **Common issues with quick fixes:**
        - **"API key invalid"** -> Run `clio /api` to configure your provider
        - **"Model not found"** -> Check available models with `clio --list-models`
        - **"Session not loading"** -> Try `clio --new` for a fresh session
        - **"Permission denied"** -> Check sandbox mode: `--sandbox` restricts file access
        
        If you've tried troubleshooting and still have an issue, please continue below.

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Checklist
      description: Please confirm you've tried these steps
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues
          required: true
        - label: I have tried running with `--debug` flag
          required: true
        - label: I am using the latest version of CLIO
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run `clio --new`
        2. Enter '...'
        3. Use tool '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: CLIO should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, CLIO...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Which area is affected?
      description: Select the component that's experiencing issues
      options:
        - Terminal UI / Chat Interface
        - Tool Execution (file_operations, terminal_operations, etc.)
        - API / Provider Integration (GitHub Copilot, OpenAI, etc.)
        - Session Management
        - Memory / Context
        - Git / Version Control
        - Multi-Agent / Sub-Agents
        - Remote Execution
        - Configuration
        - Installation / Setup
        - Performance / Crashes
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: CLIO Version
      description: What version of CLIO are you using? (Run `clio --version` or check VERSION file)
      placeholder: "e.g., 20260214.1"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "e.g., macOS 14.3, Ubuntu 24.04, WSL2"
    validations:
      required: true

  - type: input
    id: perl
    attributes:
      label: Perl Version
      description: What version of Perl are you using? (Run `perl -v`)
      placeholder: "e.g., v5.38.2"
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: AI Provider
      description: Which AI provider were you using when the issue occurred?
      options:
        - GitHub Copilot
        - OpenAI
        - Anthropic (Claude)
        - Google (Gemini)
        - OpenRouter
        - Local / Self-hosted
        - Other
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this occur?
      description: Helps us understand if it's intermittent or consistent
      options:
        - Every time (100% reproducible)
        - Most of the time (>50%)
        - Sometimes (<50%)
        - Rarely (hard to reproduce)
        - Only happened once
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Debug Output
      description: |
        Please paste the output from running with `--debug` flag.
        **Tip:** Remove any API keys or personal information before pasting!
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Did this work in a previous version?
        - What terminal are you using?
        - Are there any error messages?
