#!/usr/bin/perl
# Regression test for the cache hit collapse bug.
#
# Bug: When validate_and_truncate generates a summary on the first trim,
# it inserts the summary at position [1+] (right after system_prompt).
# This breaks the token-level LCP at the chat template boundary
# (`<system>...</system>\n<system>...</system>` vs
#  `<system>...</system>\n<user>...</user>`) and degrades sim_best
# from ~0.99 to ~0.58 forever.
#
# Fix: Move the summary to the END of the trimmed messages so that
# the LCP can extend through the stable dialog/tool_results before
# breaking at the summary content boundary.
#
# This test verifies that after validate_and_truncate, the summary
# is at the LAST position (not the second position) so the LCP
# prefix stays stable.

use strict;
use warnings;
use utf8;
use lib '/home/deck/repositories/CLIO/lib';

use Test::More;
use CLIO::Core::API::MessageValidator qw(validate_and_truncate);
use CLIO::Memory::TokenEstimator;

subtest 'summary placement: should be at the END, not at position [1+]' => sub {
    # Build a long conversation that will trigger a trim
    my @messages;
    push @messages, { role => 'system', content => 'You are CLIO. ' . ('stable system prompt. ' x 5000) };
    push @messages, { role => 'user',   content => 'Please investigate the codebase thoroughly.' };

    # Add many user/assistant exchanges to push past the trim threshold
    for my $i (1..30) {
        push @messages, { role => 'assistant', content => "Working on task $i: " . ('analysis content. ' x 200) };
        push @messages, { role => 'tool', tool_call_id => "tc_$i", content => ('x' x 4000) };
        push @messages, { role => 'assistant', content => "Result for task $i: " . ('analysis. ' x 100) };
        push @messages, { role => 'user',      content => "Continue with step $i." };
    }

    # Push past the trim threshold with low budget
    my $trimmed = validate_and_truncate(
        messages           => \@messages,
        model_capabilities => { max_context_window_tokens => 8000, max_output_tokens => 1000, supports_tools => 1 },
        tools              => [{}],
        token_ratio        => 2.5,
        api_base           => 'http://localhost:9090',
        debug              => 0,
        model              => 'test',
    );

    # Verify summary was generated
    my @summaries = grep {
        ($_->{role} // '') eq 'system'
            && ($_->{content} // '') =~ /<threadSummary>/
    } @$trimmed;

    ok(scalar(@summaries) >= 1, 'Summary was generated by validate_and_truncate');

    if (@summaries) {
        # Find the position of the summary in the trimmed messages
        my $summary_idx;
        for my $i (0 .. $#$trimmed) {
            if (($trimmed->[$i]{role} // '') eq 'system'
                && ($trimmed->[$i]{content} // '') =~ /<threadSummary>/) {
                $summary_idx = $i;
                last;
            }
        }

        # The summary should be at the END of the trimmed messages,
        # AFTER all dialog and tool_results, so that the LCP can
        # extend through the stable prefix (system + dialog + tool_results)
        # before breaking at the summary content boundary.
        my $last_idx = $#$trimmed;

        diag("Summary at index $summary_idx of $last_idx");

        is($summary_idx, $last_idx,
            'Summary should be the LAST message (preserves LCP through stable prefix)');

        # Also verify the summary is NOT right after the system prompt
        isnt($summary_idx, 1,
            'Summary should NOT be at position 1 (breaks LCP at chat template boundary)');
    }
};

done_testing();